### ISSUE TITLE
Support Towny War (Siege War)

### ISSUE THREAD

**Issue by BartosB13** [Agaloth/TownyWild#1]
Hello, I have a question, is it possible to add support for Siege War? 
The main thing is that in the siege zone and around the Siege Gathering the effect of the TownyWild plug will not work.

Siege-War wiki:
https://github.com/TownyAdvanced/SiegeWar/wiki/Siege-War-User-Guide#fire-start-a-siege

**Comment by Agaloth** [comment]
Hey there! Could you perhaps record a video so I can get a visual representation of what and when to do the effect for the protection?

**Comment by Agaloth** [comment]
I wasn't even aware about the Albion online thing haha, but I'll take a look later today to this, thanks for bringing it up!

**Comment by BartosB13** [comment]
Will you let me know later if it is possible to add support for the SiegeWar plugin?

**Comment by Agaloth** [comment]
Yeah I will lyk

**Comment by Agaloth** [comment]
Do you have discord by the way? Add me Agaloth#4927

**Comment by Agaloth** [comment]
This should work now, feel free to reopen it if you see anything wrong with it
